image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 25
- port: 8000


# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: composer install && npm install && php artisan migrate && php artisan db:seed && php artisan key:generate
- init: mysql -e "CREATE DATABASE laravel;"
- name: Run
  command: npm run dev --watch
- name: Serve
  command: php artisan serve --host=0.0.0.0

vscode:
  extensions:
    - onecentlin.laravel-blade@1.20.0:cRpyKxGh7po7Nes2YsNVLg==
    - onecentlin.laravel5-snippets@1.7.0:JKrBA6LuplbfnBfXDekUJQ==
    - mikestead.dotenv@1.0.1:SSXjr5hZcbqSF7nMIhTNnA==
    - codingyu.laravel-goto-view@1.3.2:/X4feuItKv1nRbtB60jaKQ==
    - mtxr.sqltools@0.21.3:5WWpriPAQ/xVVv27Bbi2fA==
    - bmewburn.vscode-intelephense-client@1.2.3:3EBGRE70flX1xI3ODmVhCQ==
    - felixfbecker.php-debug@1.13.0:WX8Y3EpQk3zgahy41yJtNQ==
    - stef-k.laravel-goto-controller@0.0.7:eOFkf9bmyT5gowfGevj2vA==
    - amiralizadeh9480.laravel-extra-intellisense@0.2.3:peKDuL2tK0GxaD1BZ1OX0A==
    - bradlc.vscode-tailwindcss@0.2.0:PwefoJooyem7BVrpU3Bjww==
    - octref.vetur@0.22.6:xXCsvthKcTcJhinOkpQTjQ==
    - mblode.pretty-formatter@0.1.7:vsGSnOMrxrqG+GJ04/yr/Q==
